name = "tv-shows-api"
main = "src/index.js"
compatibility_date = "2023-05-18"

account_id = '8259f9bfa45a74a587d6a90822de442d'
workers_dev = true

kv_namespaces = [
  { binding = "KV_TV_SHOWS", id = "b62c83dd4c614b5bbe512f6cb2ed8ba5", preview_id = "b62c83dd4c614b5bbe512f6cb2ed8ba5" }
]

[[d1_databases]]
  binding = "DB"
  database_name = "tv_shows"
  database_id = "<unique-ID-for-your-database>"